version: "3.3"

services:
  mm:
    image: misi/mm:3.3
    working_dir: /opt/multiparty-meeting/server
    restart: unless-stopped
    environment:
      - BASEDIR=/opt
      - MM=multiparty-meeting
      - NODE_ENV=production
    volumes:
      - ./configs/server:/opt/multiparty-meeting/server/config
      - ./configs/app:/opt/multiparty-meeting/server/public/config
      - ./certs:/opt/multiparty-meeting/server/certs
      - ./images:/opt/multiparty-meeting/server/public/images
    network_mode: "host"
    stdin_open: true
    tty: true
    container_name: mm
  redis:
    image: redis
    network_mode: "host"
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    volumes:
      - ./configs/redis:/usr/local/etc/redis
  coturn:
    image: instrumentisto/coturn
    network_mode: "host"
    stop_signal: SIGKILL
    restart: unless-stopped
    volumes:
     - ./coturn.conf:/etc/coturn/turnserver.conf
  #nodeexporter:
  #  image: prom/node-exporter
  #  network_mode: "host"
  #  ports:
  #    - '127.0.0.1:9100:9100'
  #  restart: unless-stopped
  exporter:
    image: 'marckhouzam/custom-prometheus-exporter'
    restart: unless-stopped
    network_mode: "host"
    #ports:
    #  - '8081:8081'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './exporter-config.yml:/edumeet-exporter.yaml'
      - './network_bitrate.sh:/network_bitrate.sh'
    command: '-f /edumeet-exporter.yaml'
